### ISSUE TITLE
Questions about dataloader

### ISSUE THREAD

**Issue by FightingEveryDay0** [lixsh6/Tencent_wsdm_cup2023#1]
When running ./pytorch_pretrain/pretrain, an error occurs:
```
03/07/2023 21:10:18 - INFO - __main__ -   Training/evaluation parameters PreTrainingArguments(
_n_gpu=4,
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
bf16=False,
bf16_full_eval=False,
cache_chunk_size=-1,
continue_train=True,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=2,
dataloader_pin_memory=True,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=False,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=True,
eval_accumulation_steps=None,
eval_delay=0,
eval_steps=20,
evaluation_strategy=IntervalStrategy.STEPS,
fp16=True,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
greater_is_better=True,
group_by_length=False,
half_precision_backend=auto,
hub_model_id=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=True,
label_names=['qids', 'labels', 'freqs'],
label_smoothing_factor=0.0,
learning_rate=5e-06,
length_column_name=length,
load_best_model_at_end=False,
local_rank=-1,
log_level=-1,
log_level_replica=-1,
log_on_each_node=True,
logging_dir=/home/wangyiting/first/data//outputs/pretrain/test/runs/Mar07_21-10-14_localhost.localdomain,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=20,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_type=SchedulerType.CONSTANT,
max_grad_norm=1.0,
max_steps=50000,
metric_for_best_model=annotate_all_dcg@10,
mlm_loss_weight=1.0,
mp_parameters=,
no_cuda=False,
num_train_epochs=1.0,
optim=OptimizerNames.ADAMW_HF,
output_dir=/home/wangyiting/first/data//outputs/pretrain/test,
overwrite_output_dir=True,
past_index=-1,
per_device_eval_batch_size=64,
per_device_train_batch_size=2,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
remove_unused_columns=False,
report_to=[],
resume_from_checkpoint=None,
run_name=/home/wangyiting/first/data//outputs/pretrain/test,
save_on_each_node=False,
save_steps=20,
save_strategy=IntervalStrategy.STEPS,
save_total_limit=20,
seed=2023,
sharded_ddp=[],
skip_memory_metrics=True,
temperature=1.0,
tf32=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
train_group_size=2,
use_legacy_prediction_loop=False,
warmup_ratio=0.0,
warmup_steps=0,
weight_decay=0.01,
xpu_backend=None,
)
03/07/2023 21:10:23 - INFO - pretrain.dataset -   load annotated data from /home/wangyiting/first/data//annotate_data/test_data.txt
03/07/2023 21:10:52 - INFO - pretrain.dataset -   load logged click data from /home/wangyiting/first/data/data/part-00000
============begin loading model-------------------
[INFO|configuration_utils.py:652] 2023-03-07 21:10:54,343 >> loading configuration file /home/wangyiting/first/Tencent_wsdm_cup2023-main/pytorch_pretrain/init_model/config.json
[INFO|configuration_utils.py:690] 2023-03-07 21:10:54,344 >> Model config BertConfig {
  "_name_or_path": "/home/wangyiting/first/Tencent_wsdm_cup2023-main/pytorch_pretrain/init_model/config.json",
  "architectures": [
    "CTRPretrainingModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "torch_dtype": "float32",
  "transformers_version": "4.18.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 22000
}

[INFO|trainer.py:426] 2023-03-07 21:11:01,121 >> max_steps is given, it will override any value given in num_train_epochs
[INFO|trainer.py:453] 2023-03-07 21:11:01,121 >> Using amp half precision backend
/home/wangyiting/anaconda3/envs/first/lib/python3.6/site-packages/transformers/optimization.py:309: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  FutureWarning,
[INFO|trainer.py:1290] 2023-03-07 21:11:01,127 >> ***** Running training *****
[INFO|trainer.py:1291] 2023-03-07 21:11:01,127 >>   Num examples = 400000
[INFO|trainer.py:1292] 2023-03-07 21:11:01,127 >>   Num Epochs = 9223372036854775807
[INFO|trainer.py:1293] 2023-03-07 21:11:01,127 >>   Instantaneous batch size per device = 2
[INFO|trainer.py:1294] 2023-03-07 21:11:01,127 >>   Total train batch size (w. parallel, distributed & accumulation) = 8
[INFO|trainer.py:1295] 2023-03-07 21:11:01,127 >>   Gradient Accumulation steps = 1
[INFO|trainer.py:1296] 2023-03-07 21:11:01,127 >>   Total optimization steps = 50000
  0%|                                                                                                                                                                                                   | 0/50000 [00:00<?, ?it/s]03/07/2023 21:11:01 - INFO - pretrain.dataset -   load file: part-00003.gz
03/07/2023 21:11:01 - INFO - pretrain.dataset -   load file: part-00008.gz
03/07/2023 21:11:03 - INFO - pretrain.dataset -   load file: part-00101.gz
03/07/2023 21:11:03 - INFO - pretrain.dataset -   load file: part-00001.gz
03/07/2023 21:11:06 - INFO - pretrain.dataset -   load file: part-00017.gz
03/07/2023 21:11:06 - INFO - pretrain.dataset -   load file: part-00007.gz
03/07/2023 21:11:08 - INFO - pretrain.dataset -   load file: part-00014.gz
03/07/2023 21:11:08 - INFO - pretrain.dataset -   load file: part-00009.gz
03/07/2023 21:11:10 - INFO - pretrain.dataset -   load file: part-00005.gz
03/07/2023 21:11:10 - INFO - pretrain.dataset -   load file: part-00012.gz
03/07/2023 21:11:13 - INFO - pretrain.dataset -   load file: part-00002.gz
03/07/2023 21:11:13 - INFO - pretrain.dataset -   load file: part-00016.gz
03/07/2023 21:11:15 - INFO - pretrain.dataset -   load file: part-00006.gz
03/07/2023 21:11:15 - INFO - pretrain.dataset -   load file: part-00018.gz
03/07/2023 21:11:17 - INFO - pretrain.dataset -   load file: part-00010.gz
03/07/2023 21:11:18 - INFO - pretrain.dataset -   load file: part-00011.gz
03/07/2023 21:11:20 - INFO - pretrain.dataset -   load file: part-00019.gz
03/07/2023 21:11:20 - INFO - pretrain.dataset -   load file: part-00015.gz
03/07/2023 21:11:22 - INFO - pretrain.dataset -   load file: part-00013.gz
[WARNING|trainer.py:1506] 2023-03-07 21:11:25,104 >> There seems to be not a single sample in your epoch_iterator, stopping training at step 0! This is expected if you're using an IterableDataset and set num_steps (50000) higher than the number of available samples.
[INFO|trainer.py:1531] 2023-03-07 21:11:25,104 >> 

Training completed. Do not forget to share your model on huggingface.co/models =)


Traceback (most recent call last):
  File "/home/wangyiting/first/Tencent_wsdm_cup2023-main/pytorch_pretrain/pretrain/run.py", line 151, in <module>
    main()
  File "/home/wangyiting/first/Tencent_wsdm_cup2023-main/pytorch_pretrain/pretrain/run.py", line 142, in main
    trainer.train(resume_from_checkpoint=resume_model_path)
  File "/home/wangyiting/anaconda3/envs/first/lib/python3.6/site-packages/transformers/trainer.py", line 1570, in train
    train_loss = self._total_loss_scalar / self.state.global_step
ZeroDivisionError: float division by zero
  0%|                                                                                                                                                                                                   | 0/50000 [00:26<?, ?it/s]
```

**Comment by FightingEveryDay0** [comment]
The reason maybe lacking of enough training data.
